.gitignore
brigade/core/task.py
demo/configure.py

Some of the demo examples still used a dict for the results.

Change remaining demo result from dict to object

---

brigade/plugins/tasks/networking/netmiko_generic.py
brigade/plugins/tasks/networking/netmiko_ssh.py
requirements-dev.txt

Note, I didn't include netmiko as a requirement to the brigade package.

Added  `netmiko_ssh` task to run any netmiko method

---

requirements.txt
tox.ini

Remove develop branch of netmiko

---

brigade/core/task.py
tests/core/test_tasks.py

The idea is to be able to run subtasks in the same way we run tasks. See the test for an example.

added task.run to help executing subtasks

---

.gitignore
brigade/plugins/tasks/networking/__init__.py
brigade/plugins/tasks/networking/netmiko_send_command.py
brigade/plugins/tasks/networking/netmiko_send_config.py
tests/plugins/tasks/networking/test_netmiko_send_config.py

Re-submit https://github.com/napalm-automation/brigade/pull/67 to fix rebase issue and to add unit tests.

Re-add netmiko send_config

---

brigade/plugins/tasks/connections/netmiko_connection.py

Incorrect entry for IOS-XR in netmiko map

---

docs/tutorials/intro/install.rst

I used Python 2.7 mostly to show to upgrade pip earlier, but it's better if everything is Python 3.6.

Use Python 3.6 as default in the tutorial.

---

README.md

Since we don't really use the master branch.

Swap from master to develop branch for badges

---

nornir/core/__init__.py
nornir/core/configuration.py

Fix issues with using built-in and overwriting variable with loop variable

---

nornir/core/inventory.py

Fix docstring change "all" group to "defaults"

---

docs/howto/writing_a_custom_inventory.rst

Modify howto to use InitNornir & fix group -> groups

---

nornir/core/filter.py
tests/core/test_filter.py

For instance:
```
def test_filtering_list_any(self):
f = F(nested_data__a_list__any=[1, 3])
filtered = sorted(list((inventory.filter(f).hosts.keys())))
assert filtered == ["dev1.group_1", "dev2.group_1"]
def test_filtering_list_all(self):
f = F(nested_data__a_list__all=[1, 2])
filtered = sorted(list((inventory.filter(f).hosts.keys())))
assert filtered == ["dev1.group_1"]
```

Filter collections by any/all

---

nornir/core/configuration.py
nornir/plugins/inventory/simple.py
nornir/plugins/tasks/data/load_yaml.py
tests/plugins/inventory/test_ansible.py

This bring loading a YAML file with 100k lines down to 3s from 35s.

use C loader for ruamel.yaml

---

docs/howto/handling_connections.ipynb
nornir/core/__init__.py
nornir/core/configuration.py
nornir/core/deserializer/configuration.py
nornir/core/deserializer/inventory.py
nornir/core/inventory.py
nornir/init_nornir.py
nornir/plugins/tasks/commands/remote_command.py
nornir/plugins/tasks/files/sftp.py
nornir/plugins/tasks/networking/napalm_cli.py
nornir/plugins/tasks/networking/napalm_configure.py
nornir/plugins/tasks/networking/napalm_get.py
nornir/plugins/tasks/networking/napalm_validate.py
nornir/plugins/tasks/networking/netmiko_file_transfer.py
nornir/plugins/tasks/networking/netmiko_send_command.py
nornir/plugins/tasks/networking/netmiko_send_config.py
tests/core/test_connections.py
tests/plugins/functions/text/test_print_result.py
tests/plugins/tasks/networking/test_napalm_cli.py
tests/plugins/tasks/networking/test_napalm_configure.py
tests/plugins/tasks/networking/test_napalm_get.py
tests/plugins/tasks/networking/test_napalm_validate.py

I am trying to get rid of as much magic as possible.
Solves #252

remove need of Config object in the Inventory and Hosts

---

nornir/plugins/inventory/netbox.py

Add query capabilities to netbox

---

nornir/plugins/tasks/networking/__init__.py
nornir/plugins/tasks/networking/netmiko_save_config.py

Add plugin for netmiko's save_config() method.
Not sure how I can develop a test case for this, so help / suggestions would be welcome.

Plugin for netmiko save_config() method

---

requirements-dev.txt

Looks like pytest 4.1.0 breaks things...

fix pytest

---

nornir/plugins/connections/napalm.py
nornir/plugins/connections/netmiko.py

Add support for SSH config file via Nornir config for Netmiko and NAPALM

---

docs/howto/advanced_filtering.ipynb
docs/howto/transforming_inventory_data.ipynb
docs/howto/writing_a_custom_inventory_plugin.ipynb

While reading over the guides, I found some random typos.

Document typos

---

nornir/plugins/functions/text/__init__.py

Print result

---

.travis.yml
CHANGELOG.rst
pyproject.toml

fix minor deployment issues

---

README.md

@dmfigol @ogenstad @ktbyers any opinions/missing resources about this? Format could also be better, if you have suggestions let me know :)

added external resources

---

docs/plugins/tasks/version_control/gitlab.ipynb
docs/tutorials/intro/grouping_tasks.ipynb
nornir/core/__init__.py
nornir/core/inventory.py

patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ).

spelling fixes

---

nornir/plugins/inventory/netbox.py
tests/plugins/inventory/netbox/2.3.5/mocked/devices-0.json
tests/plugins/inventory/netbox/2.3.5/mocked/devices-1.json
tests/plugins/inventory/netbox/2.3.5/mocked/devices-2.json
tests/plugins/inventory/netbox/2.3.5/mocked/devices.json
tests/plugins/inventory/test_netbox.py

Fixes netbox pagination.
This fixes the same issue as #361. The owner of that PR didn't have the time to continue to work on the PR & I needed a solution so I implemented a solution myself.
I have discussed this @bdlamprecht and he was ok with the approach.

Fix netbox pagination

---

nornir/core/inventory.py
nornir/core/state.py
tests/core/test_inventory.py

Ref https://github.com/nornir-automation/nornir/issues/393
* Add `dict()` method to `Inventory` class.
* Point `get_inventory_dict` to `dict()` method in Inventory
* Refactor `to_dict()` method of `GlobalState` and rename to `dict()` to match reference in `Nornir` class

Fix Nornir dict method and dependencies

---

tests/core/test_inventory.py
tests/inventory_data/defaults.yaml

Adds unittests for some of the functions on Inventory.Host that weren't tested.

Add tests for Host data functions

---

nornir/core/inventory.py

https://github.com/nornir-automation/nornir/issues/429

Fix KeyError when setting a "False" val in defaults

---

nornir/plugins/tasks/networking/__init__.py
nornir/plugins/tasks/networking/netconf_edit_config.py
nornir/plugins/tasks/networking/netconf_get.py
nornir/plugins/tasks/networking/netconf_get_config.py
tests/plugins/tasks/networking/test_netconf_edit_config.py
tests/plugins/tasks/networking/test_netconf_get.py
tests/plugins/tasks/networking/test_netconf_get_config.py

* netconf_edit_config
* netconf_get
* netconf_get_config

Add netconf plugins

---

nornir/core/__init__.py

This pull request replaces `multiprocessing.dummy.Pool` with `concurrent.futures.ThreadPoolExecutor`.
Reasons for change:
- import of `multiprocessing` is misleading, because we are using threads, not multiple processes. We already had a situation when people looking at the source code were surprised
- `multiprocessing.dummy` [docs](https://docs.python.org/3.6/library/multiprocessing.html#module-multiprocessing.dummy) are lacking compared to `concurrent.futures` [ThreadPoolExecutor](https://docs.python.org/3.6/library/concurrent.futures.html#threadpoolexecutor) and [ProcessPoolExecutor](https://docs.python.org/3.6/library/concurrent.futures.html#processpoolexecutor)
I've also done performance testing. I was using this task on 500 hosts with 125 workers:
```
def useless_task(task): …
```

Replace multiprocessing.dummy with concurrent.futures

---

nornir/plugins/tasks/networking/__init__.py
nornir/plugins/tasks/networking/napalm_ping.py

Add napalm_ping plugin to nornir

napalm_ping.py

---

poetry.lock
pyproject.toml
setup.cfg

Remove flake8-import-order

---

README.md
docs/index.rst

Explicitly mention in docs/readme that Python 3.6.2+ is supported 

---

docs/plugins/tasks/version_control/gitlab.ipynb

Delete /tmp/hosts before running gitlab plugin notebook cell

---

nornir/core/__init__.py
nornir/core/task.py
pyproject.toml

regression: pass nornir object to task

---

.github/workflows/main.yaml
pyproject.toml

It's a bit slow for my taste but does the job:
https://github.com/nornir-automation/nornir/releases/tag/v3.0.0a4
https://github.com/nornir-automation/nornir/runs/680811243?check_suite_focus=true#step:6:19

fix publishing to pypi

---

nornir/plugins/tasks/networking/napalm_ping.py

Issue: napalm_ping error when source is not specified #555

Remove None default for source of napalm_ping

---

nornir/core/configuration.py

Fixes bug with logging configuration from config.yaml file not working.

Nornir 3.x: Fix logging bug

---

docs/tutorial/inventory.ipynb

nornir-automation#562
Change the references to inventory, groups, hosts, defaults, host from "Reference Guides" to "API Documentation".
No

Fix linking problems in tutorial Inventory.ipynb

---

docs/tutorial/inventory.ipynb

Fix nornir_nos filter in inventory tutorial

---

.github/workflows/main.yaml
poetry.lock

For more info: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

fix "GitHub Actions: Deprecating set-env and add-path commands"

---

nornir/plugins/inventory/simple.py

Fixes a bug identified in the discussion here: https://github.com/nornir-automation/nornir/discussions/673

Evaluate a host's group after groups evaluation in SimpleInventory

---

docs/index.rst

docs/index.rst Fix typo

---

docs/howto/filtering_deep_dive.ipynb

site_type = secondary below this line, this is a remark typo

Fix typo tertiary --> secondary

---

.github/workflows/main.yaml
Makefile
docs/conf.py

Fixes #932
I resolved the issue with the sphinx build and removed the need for the `sphinx` make command, as there is already a `docs` command available.

Fix Sphinx add custom css issue

---

.readthedocs.yml

See:
https://github.com/python-poetry/poetry/issues/9025

Update RTD config to have poetry properly use RTD venv

---

docs/highlighter.py
pyproject.toml

Add typehints in highlighter and correct import from IPython (HTML is not exported from IPython.display)

Fix highlighter typehints and use correct import path

---

nornir/core/exceptions.py
nornir/core/task.py
pyproject.toml
tests/core/test_InitNornir.py

Add missing return type annotation for special method `__init__

---

nornir/core/__init__.py
pyproject.toml

Rename name -> hostname to avoid redefining argument with the local name

---

.github/workflows/main.yaml
Makefile

Reactivate coveralls

---

docs/community/plugin_list.rst
docs/index.rst
docs/plugins/index.rst

According to the discussion in #988 this PR adds the plugin list to the regular Nornir docs.

Add pulgin list to the nornir docs

---

nornir/core/task.py
tests/core/test_pickle.py

Ref https://github.com/nornir-automation/nornir/issues/994

fix to allow pickling Result objects
