nornir-automation/nornir

- brigade/core/inventory.py
- tests/core/inventory_data/hosts.yaml
- tests/core/test_inventory.py
The current filter function requires that the filters being used are defined on all of the hosts in the inventory.
> [bugfix] - `filter` method fails if a host doesn't have one of the filtering keys

- brigade/core/__init__.py
Some tasks might have to run in serial, this change allowes a user to
change the number of workers for a specific task without changing the
value of Brigade.num_workers
> Add `num_workers` argument to `run()`

- brigade/core/__init__.py
Fixing a typo in `_run_parallel()`.
> Store traceback instead of exc

- .gitignore
- brigade/core/__init__.py
- brigade/core/configuration.py
- brigade/plugins/tasks/connections/paramiko_connection.py
- docs/_data_templates/configuration-parameters.j2
- docs/conf.py
- docs/ref/api/configuration.rst
- docs/ref/api/index.rst
- docs/ref/configuration/index.rst
- docs/ref/index.rst
Something like this could work regarding `ssh_connection` in #25.
Could also ship a SimpleYaml config plugin similar to the SimpleInventory one.
Currently one would access the variables with `task.brigade.config.ssh_config_file` which seems a bit long, so perhaps some shortcut is needed.
> For discussion - Add config class

- brigade/plugins/tasks/connections/napalm_connection.py
- brigade/plugins/tasks/connections/netmiko_connection.py
- brigade/plugins/tasks/connections/paramiko_connection.py
@ogenstad brought up that after moving the connection to a task `host` is no longer needed, which is true, so I am removing it. This also simplifies netmiko's connection as there is no longer a collision.
@ktbyers @ogenstad
> removing host from connection tasks as it's no longer needed

- brigade/core/configuration.py
The idea is that I want to be able to do:
```
brigade = Brigade(
inventory=SimpleInventory("../hosts.yaml", "../groups.yaml"),
dry_run=True,
config=Config(raise_on_error=False),
) 
```
> making Config configurable programmatically

- brigade/core/configuration.py
- docs/_data_templates/configuration-parameters.j2
The previous PR's introduced configuration types where the values can be
a list or a dictionary, this commit restricts the environment variables
so that only int, str and bool type settings can be configured using
environment variables.
> Only allow int, str and bool environment variables

- .gitignore
- brigade/plugins/inventory/nsot.py
I have added support for providing nsot parameters in config.yaml (and load it with InitBrigade). I also added support for additional nsot parameters, so that both auth_methods (auth_header/auth_token) can be used.
> support more nsot parameters and auth_methods

- .gitignore
- Makefile
Currently the nsot.sqlite3 database always changes when running tests
this PR is a workaround where we instead copy the database to a
temporary file before starting the tests.
> Fix to simplify local testing with tox

- brigade/core/__init__.py
- brigade/core/configuration.py
- tests/core/test_InitBrigade.py
Hi,
as discussed I implemented the possibility to define a transform_function for an inventory (e.g. nsot) either as function arg of InitBrigade or directly in the config.yaml. 
Example of giving it in the config.yaml is:
transform_function: simon.test.transform_function.adapt_host_data
-> simon.test.transform_function has to be a module which could be imported. adapt_host_data() is the function.
> Transform function can be given as function arg (InitBrigade) or in config.yaml

- brigade/core/__init__.py
- brigade/core/task.py
- brigade/plugins/tasks/files/sftp.py
- brigade/plugins/tasks/files/write_file.py
- brigade/plugins/tasks/networking/napalm_configure.py
The purpose of this is two-fold:
1. Simplify dry_run logic by moving it to the task directly.
2. Make it clearer which tasks support "dry_run" or not
By removing the `dry_run` logic from the core and transferring it to the tasks we basically get rid of code which only purpose is to move things around and we also make it clearer which tasks support it as now to override argument is part of the task signature.
> Move dry_run logic to the task

- brigade/plugins/tasks/apis/__init__.py
- brigade/plugins/tasks/apis/http_method.py
- docs/ref/tasks/apis.rst
- docs/ref/tasks/index.rst
- tests/plugins/tasks/apis/test_http_method.py
Note that the way it's designed it can be used with both:
```
b.run(http_method,
method="get",
url="http://.../")
```
and standalone as
```
result = http_method(url="http://.../", method="get", ...)
```
> added http_method task

- brigade/core/helpers/__init__.py
- brigade/plugins/tasks/commands/command.py
- brigade/plugins/tasks/data/load_json.py
- brigade/plugins/tasks/data/load_yaml.py
- brigade/plugins/tasks/files/sftp.py
- brigade/plugins/tasks/networking/napalm_configure.py
- brigade/plugins/tasks/text/template_file.py
- tests/plugins/tasks/commands/test_command.py
- tests/plugins/tasks/files/test_sftp.py
- tests/plugins/tasks/networking/test_napalm_validate.py
It was used very inconsistently so let's remove it. If we want it later on we can try to add it via a decorator or something like that.
Solves #107
> remove automatic resolver

- brigade/core/configuration.py
- brigade/core/helpers/jinja_helper.py
- brigade/plugins/tasks/text/template_file.py
- brigade/plugins/tasks/text/template_string.py
For instance:
```
def get_filters():
return {"test": test}
def test(data):
return "yes!!!"
```
and then:
```
brg = InitBrigade(
dry_run=dry_run,
SimpleInventory={"host_file": HOSTS_FILE, "group_file": GROUPS_FILE},
jinja_filters="jinja_filters.get_filters",
)
```
> add mechanism to pass jinja_filters

- MANIFEST.in
- README.md
- setup.py
With today's launch of the new pypi we can now have markdown files to describe the project. Currently Brigade doesn't have a description on https://pypi.org/project/brigade/, this will add the README.md to the package so that it can be displayed on the pypi page.
> Add description to package for display on pypi.

- brigade/plugins/functions/text/__init__.py
- brigade/plugins/tasks/commands/remote_command.py
- brigade/plugins/tasks/networking/tcp_ping.py
- tests/plugins/tasks/networking/test_tcp_ping.py
Should we also add / change other plugins to always have the most important output in "result"?
Don't know if that would be diff or changed in something like napalm_configure().
> Add result key and cleanup

- brigade/core/task.py
- tests/core/test_tasks.py
Without this a grouped task with a failing task won't stop and will keep running the rest of the tasks in the same group. For instance:
```
def grouped_tasks(task):
task.run(task=this_task_fails)
task.run(task=another_task)
brigade.run(task=grouped_tasks)
```
Without this patch `another_task` will run even if `this_task_fails`. With this patch, you have to catch if if you want to keep going.
> dont mask error when running a grouped task

- tests/core/test_inventory.py
The documentation states that the has_parent_group takes an object as
its argument. Don't know if it would be better with just a string or if
it's better the way it is now?
> Add test for has_parent_group()

- brigade/core/exceptions.py
- brigade/core/task.py
- setup.py
- tests/plugins/functions/text/output_data/failed_with_severity.stdout
- tests/plugins/functions/text/output_data/failed_with_severity_python27.stdout
Raises BrigadeSubTaskError when a subtask to a grouped task has failed,
this allows for a prettier error message when using print_output()
I haven't changed the output from the tests for print_output yet so currently this will fail.
With a test script:
```python
from brigade.core import InitBrigade
from brigade.plugins.functions.text import print_result
from brigade.core.task import Result
brg = InitBrigade(
raise_on_error=False)
def greet(task, msg):
return Result(host=task.host, result="{}".format(msg))
def fail_on_me(task):
with open('does_not_exist.txt', 'r') as fs:
data = fs.read()
return Result(host=task.host, result=data)
def sub_task(task):
task.run(task=greet, msg="first")
task.run(task=greet, msg="second")
task.run(task=fail_on_me)
task.run(task=greet, msg="third")
return …
```
> Add BrigadeSubTaskError for grouped tasks

- brigade/plugins/tasks/connections/napalm_connection.py
For Cisco IOS and for NXOS_SSH, Brigade user's might logically define a `brigade_ssh_port` in inventory.
Consequently, I think it is logical that we should process them in this order:
1. optional_args['port']
2. brigade_network_api_port
3. brigade_ssh_port
> NAPALM connection fallback to ssh_port if no optional_args and no API port defined

- nornir/plugins/tasks/connections/napalm_connection.py
The current docstring is wrong and can cause confusion.
Another solution would be to point to `task.host.network_api_port` but before we have a specific section in the documentation which talks about how these are connected I think it's better to point to the key as in this PR.
> Clarify which key is used for the Napalm port

- nornir/core/__init__.py
- nornir/core/inventory.py
- tests/core/test_inventory.py
To discuss, might be nice if we can dump with a `to_dict` an inventory object and make it load back into the same object. I think we should bother about doing it as a `dict` instead of as a `json` or any other format as each one of them have a different mechanism to deal with custom objects and we should assume they should work.
Basically what I'd like to do here is make sure that we can do something equivalent to `my_inv == Inventory(my_inv.to_dict())`
> add to_dict function so the inventory is serializable

- nornir/core/configuration.py
- nornir/plugins/inventory/ansible.py
- nornir/plugins/inventory/simple.py
- nornir/plugins/tasks/data/load_yaml.py
- tests/plugins/inventory/test_ansible.py
`ruamel.yaml.safe_load` is being deprecated: https://yaml.readthedocs.io/en/latest/api.html
Replaced it with `ruamel.yaml.YAML()`.
It accepts the stream directly (no need to read it first).
Arguments like `default_flow_style` are set on the `YAML` object as attribute.
Also, different parameters like `typ="safe"`, `pure=True` are quite confusing and were clarified in this SO answer: https://stackoverflow.com/questions/51316491/ruamel-yaml-clarification-on-typ-and-pure-true
> Remove deprecated ruamel.yaml API calls

- README.md
DSL was a new acronym, at least for this usage, to me so I figured I'd add the initial expansion to the README just in case others out there don't know this usage.
> Add initial expansion of DSL acronym.

- nornir/plugins/inventory/ansible.py
I noticed that there was a leftover import for Python 2, since it's no longer supported we can remove it and clean up the code a bit.
> Remove old Python 2 import

- nornir/core/inventory.py
Calling this in some Nornir code:
```
brg.close_connections()
```
Generated a bunch of exceptions pertaining to dictionary size changing while iterating over dictionary:
```
hp_procurve: Traceback (most recent call last):
File "/home/gituser/nornir/nornir/core/task.py", line 63, in start
r = self.task(self, **self.params)
File "/home/gituser/nornir/nornir/core/__init__.py", line 247, in close_connections_task
task.host.close_connections()
File "/home/gituser/nornir/nornir/core/inventory.py", line 353, in close_connections
for connection in self.connections:
RuntimeError: dictionary changed size during iteration
```
> Patch connection close

- nornir/plugins/connections/napalm.py
My understanding is that given the following inventory:
hosts.yaml
```yaml
---
nxos1:
hostname: nxos1.twb-tech.com
groups: 
- nxos
nxos2:
hostname: nxos2.twb-tech.com
groups: 
- nxos
```
And groups.yaml:
```yaml
---
defaults: {}
nxos:
port: 443
napalm_options:
platform: nxos
connection_options:
timeout: 300
optional_args:
port: 8443
nxos_ssh:
port: 443
napalm_options:
platform: nxos_ssh
connection_options:
timeout: 300
optional_args:
port: 22
```
That the connection_options should map directly to the arguments of the driver which for the case of napalm would have `port` embedded in the `optional_args`
Or worded differently...first-level port, should not override a port specified in connection_options["optional_args"].
> Fix napalm plugin port reference

- nornir/plugins/connections/napalm.py
connection_options["optional_args"] might not exist (if it is not defined in inventory).
Consequently, I was getting an exception when "port" was defined in inventory, but "optional_args" was not defined.
parameters["optional_args"] will always exist.
> Fixing issue with napalm plugin if port but no optional_args

- nornir/core/__init__.py
- nornir/core/connections.py
- nornir/core/exceptions.py
- nornir/core/inventory.py
- nornir/plugins/connections/__init__.py
- tests/core/test_connections.py
This API can be used internally for built-in plugins and
externally by a developer of a custom connection plugin
Usage:
```
from nornir.core.connections import Connections, ConnectionPlugin
class MyConnectionPlugin(ConnectionPlugin):
...
Connections.register('my', MyConnectionPlugin)
plugin = Connections.get_plugin('my')  # used internally in open_connection
Connections.deregister('my')
```
Fixes #211 
Closes #142
> Add class methods for plugins registration in Connections class

- nornir/plugins/connections/netmiko.py
Added "nxos_ssh": "cisco_nxos" to napalm_to_netmiko_map in nornir/plugins/connections/netmiko.py.
As per the below open issue.
Netmiko missing device_type mapping from Napalm drivers including napalm community drivers #262
> Update the netmiko map with nxos_ssh

- docs/howto/transforming_inventory_data.ipynb
- nornir/core/configuration.py
- nornir/core/deserializer/configuration.py
- nornir/core/deserializer/inventory.py
- nornir/core/inventory.py
- nornir/init_nornir.py
- tests/core/deserializer/test_configuration.py
- tests/core/test_InitNornir.py
Adds support, documentation and tests for a new `transform_function_options` inventory configuration option.
Fixes #290
> Transform function options

- tests/inventory_data/external_hosts.yaml
- tests/plugins/tasks/networking/test_tcp_ping.py
By having a test for external connectivity which isn't stubbed,
what's actually being tested is the network environment of the development
machine, and not the nornir code. There are several examples where
this test would legitimately fail:
- Offline laptop
- Corporate environment with restrictive firewall policies.
As such, a failing test does not necessarily indicate an issue with the
code. A failed test will cause downstream tools that depend on passing
tests to fail, or leave developers wasting time looking for non-existent
faults.
> Remove the external ping test

- docs/index.rst
The first example in the documentation is incorrect after 2.0 was released.
```python
from nornir import InitNornir
nr = InitNornir(
config_file="nornir.yaml", dry_run=True, num_workers=20
)
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
File "/Users/patrick/.virtualenvs/meetup/lib/python3.6/site-packages/nornir/init_nornir.py", line 43, in InitNornir
conf = Config.load_from_file(config_file, **kwargs)
File "/Users/patrick/.virtualenvs/meetup/lib/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 170, in load_from_file
return Config.deserialize(**{**config_dict, **kwargs})
File "/Users/patrick/.virtualenvs/meetup/lib/python3.6/site-packages/nornir/core/deserializer/configuration.py", line 152, in deserialize
**kwargs,
File …
```
> Fix example for Nornir 2.0

- nornir/plugins/tasks/commands/remote_command.py
`commands.remote_command` hangs when receiving a large amount of output. This appears to be an ordering problem when `chan.recv_exit_status()` is called before doing a read.
This is ultimately a paramiko problem, discussed in this issue: https://github.com/paramiko/paramiko/issues/448
And this warning in the channel code that was the result of the paramiko issue linked above indicates that `chan.recv_exit_status()` should be called after a read: https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/channel.py#L387-L396
The patch in this PR resolves hanging I have experienced when dumping large routing table output from a network host running BIRD using `commands.remote_command` in nornir.
> Fix paramiko chan.recv_exit_status() call order

- nornir/plugins/functions/text/__init__.py
Per issue #319 fixing ascii color encoding for certain terminals by re-initializing colorama terminal integration at start time.
> fix issue #319 - ascii color codes appear instead of color in output

- nornir/plugins/connections/netmiko.py
Stated that this function uses the Napalm driver instead of the Netmiko driver.
> Fix comment under class Netmiko(ConnectionPlugin):

- docs/upgrading/1_to_2.rst
Highlights the requirement to move custom inventory data under
a `data` subkey when upgrading to nornir 2.x
> Update the 1-to-2 upgrade guide for custom inventory data

- docs/howto/transforming_inventory_data.ipynb
As promised in Issue #364, I've updated the howto for properly handling the `ConnectionOptions` via the `transform_function` and as well as via `nr.inventory.defaults`.
If you see any glaring errors, please let me know.
> Updating howto documentation for including 'ConnectionOptions'

- nornir/core/inventory.py
- tests/core/test_inventory.py
Added add_host and add_group functions to nornir.core.inventory.Inventory class.  Automatically maps the existing inventory defaults to the new host or group as they are dynamically created after initialization. Added unit tests to test_inventory module.
Ref: [nornir-automation/nornir Issue# 370](https://github.com/nornir-automation/nornir/issues/370)
> Added add_host and add_group functions to nornir.core.inventory.Inventory class

- nornir/core/inventory.py
- tests/core/test_inventory.py
Adding functions to nornir.core.inventory.Inventory to abstract serialization of the running inventory into dictionaries. Functions for: full inventory, defaults, groups, and hosts. This makes the inventory available in an exportable format that users could then build plugins to push out into various formats.
A simple future usecase would be to leverage the dicts to export to simple inventory files.  This would allow dynamically added inventory items to be captured and placed into a more permanent inventory.
> Get inventory dicts

- nornir/plugins/inventory/simple.py
- tests/plugins/inventory/test_simple.py
Solves #347 
This allows you to use either native objects or yaml files to load the SimpleInventory. For instance:
```
nr = InitNornir(inventory={
"plugin": "nornir.plugins.inventory.SimpleInventory",
"options": {
"host_file": "my_hosts.yaml",
"group_file": "my_groups.yaml",
"defaults_file": "my_defaults.yaml",
}
})
```
or:
```
nr = InitNornir(inventory={
"plugin": "nornir.plugins.inventory.SimpleInventory",
"options": {
"hosts": {
"host1": {
"username": "user",
"groups": ["group_a"],
"data": {"a": 1, "b": 2},
},
"host2": {"username": "user2", "data": {"a": 1, "b": 2}},
}
"groups": {"group_a": {"platform": "linux"}},
"defaults": {"data": {"a_default": "asd"}},
}
})
```
or a combination:
```
nr = InitNornir(inventory={
"plugin": "nornir.plugins.inventory.SimpleInventory",
"options": { …
```
> added support to initialize SimpleInventory with native objects

- README.md
Text and links are swapped in the "external resources" section.
> Fix markup for links to external resources

- nornir/core/inventory.py
- tests/core/test_inventory.py
Referencing Issue #383 
Added line on `add_host` and `add_group` methods to re-initialize inventory.  Fixes the issue of being able to add undefined parent groups to hosts and groups when they are added dynamically using those methods of the `Inventory` class.
> Fix add_host and add_group methods to re-initialize inventory

- nornir/plugins/tasks/networking/__init__.py
- nornir/plugins/tasks/networking/netmiko_commit.py
Add netmiko_commit task to support ability to write to two-stage config devices via netmiko.
> Add netmiko_commit task

- nornir/plugins/tasks/version_control/gitlab.py
While I haven't tried this plugin I don't think it was working as intended. Since the dry_run was set to `False` in gitlab() function the call to `task.is_dry_run()` would always have returned `False`, or `True` if dry_run=True had been passed to gitlab(), since task.is_dry_run() was used I assume that the idea was to default to the global setting and instead allow dry_run to be overridden on this task level.
> Gitlab plugin: Fix global dry_run check

- nornir/core/state.py
- nornir/core/task.py
- setup.cfg
Added type checking for nornir.core.task. The changes to Host, with Union[Host, None] had to do with the http_method task.
> Enable mypy for nornir.core.task

- .travis.yml
The link to the Poetry installer was pointing to a 404 url.
> Fix Poetry link in .travis.yml: Install Poetry from official link

- docs/plugins/inventory/index.rst
- docs/plugins/inventory/netbox.rst
As reported in Slack the netbox inventory plugin was missing from the documentation.
> Add Netbox inventory plugin to documentation

- nornir/plugins/inventory/netbox.py
- tests/plugins/inventory/netbox/2.3.5/expected.json
- tests/plugins/inventory/netbox/2.3.5/expected_transform_function.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices-2.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices.json
Devices in Netbox don't need to have a name defined. This is usefull
to model for example switch stacks, for which individual members don't
neceseraly need a name.
In such cases we will define the Nornir host's name to the device id
in Netbox.
> Fix netbox unnamed devices

- .gitignore
- Dockerfile
- pyproject.toml
Replaces part of #459 
Minor fixes discussed in other PR:
- Added .idea to gitignore
- Modified Dockerfile slightly -- I'm not 100% on this, but pretty sure this was just a Poetry syntax change... modified poetry config settings.virtualenvs.create false --> poetry config virtualenvs.create false. I've not really used Poetry but all the tests and such seem to work as desired and I don't get whatever error complaining about invalid setting anymore!
- Modified pyrpoject.toml setting for Black allows-prereleases --> allow-prereleases -- this was another one that just popped up saying it was/is being deported (the "allows" bit)
> cleanup items from #459

- tests/plugins/tasks/networking/test_netconf_capabilities.py
- tests/plugins/tasks/networking/test_netconf_edit_config.py
- tests/plugins/tasks/networking/test_netconf_get.py
- tests/plugins/tasks/networking/test_netconf_get_config.py
Netconf tests require docker environment up and running, so outside of that they should be marked with `@skip` marker not to fail the test suite without docker.
> Add skip mark to netconf tests

- nornir/plugins/connections/netconf.py
- tests/inventory_data/netconf_hosts.yaml
The netconf connection plugin has a small bug which sets the `ssh_config` parameter to `None` in all cases, regardless of setting it either as an extra or via the nornir global `ssh.config_file`. This causes a user's ssh config to go unused, and if you require things like ssh proxies to connect to network devices, makes the plugin unusable. Overwriting all `ssh_config` values doesn't seem intentional and may have been left over from previous testing when the plugin was developed.
Unfortunately, ncclient will not attempt to parse a ssh config (even in a default location) unless `ssh_config` is set to something other than `None`:
https://github.com/ncclient/ncclient/blob/60c3d36ed460b77ce9055ddc4a14deeddd2131dd/ncclient/transport/ssh.py#L226-L229
This PR only sets `ssh_config` to `None` if …
> Netconf connection plugin does not respect ssh config

- nornir/core/connections.py
- nornir/core/inventory.py
- tests/core/test_connections.py
With this fix failed connections are not stored in `host.connections` dictionary, which means we are not trying to close them, raising an exception.
Besides fixing bug #350, this also now allows to have a transparent retry mechanism for tasks which work with connections. Previously, any retry on the host, connection to which has failed, would leave a connection attribute uninitialized and ultimately fail.
> Do not store failed connections in host attributes

- nornir/init_nornir.py
- poetry.lock
- pyproject.toml
This PR uses `entry_points` to discover connection plugins. Currently, an external plugin has to run the following custom code on import to register itself:
```python
from nornir.core.connections import ConnectionPlugin, Connections
CONNECTION_NAME = "napalm"
class Napalm(ConnectionPlugin):
...
if CONNECTION_NAME not in Connections.available:
Connections.register(CONNECTION_NAME, Napalm)
```
With this change, the last bits are not needed and an entry_point is used instead:
``` toml
[tool.poetry.plugins."nornir.plugins.connections"]
"netmiko" = "nornir.plugins.connections.netmiko:Netmiko"
```
We may want to extend this to the inventory plugins so we can avoid requiring the long import path in the configuration. Not sure if there is any benefit to using this for tasks, at best we could …
> use entrypoints to discover connection plugins

- nornir/core/helpers/jinja_helper.py
When developing jinja templates for use with Nornir I've run in to two issues that I think we can solve by adjusting the jinja environment for template rendering.
1. If the template includes several blocks that are indented, the output also gets a strange indent. Ex:
```
{% for loop1 %}
{% if statement1 %}
{% if statement2 %}
description {{ description }}
```
All those whitespace before the {%%} blocks seems to be compounded and added before the description line, which makes it's indent look really weird in the output. If we add lstrip_blocks=True those whitespace to the left will be removed.
2. When including several files the removal of trailing whitespace might cause issues. Ex:
```
{% include 'vlan.j2' %}
{% include 'vrf.j2' %}
```
The trailing newline from the file vlan.j2 will be …
> Improved whitespace handling in jinja template rendering

- docs/upgrading/2_to_3.rst
- nornir/core/__init__.py
- nornir/core/configuration.py
- nornir/core/plugins/runners.py
- nornir/core/task.py
- nornir/init_nornir.py
- nornir/plugins/runners/__init__.py
- pyproject.toml
- setup.cfg
- tests/conftest.py
- tests/core/test_InitNornir.py
- tests/core/test_InitNornir/a_config.yaml
- tests/core/test_configuration.py
- tests/core/test_configuration/config.yaml
- tests/core/test_connections.py
- tests/core/test_tasks.py
- tests/plugins/processors/test_parallel.py
- tests/plugins/processors/test_serial.py
This PR introduces the concept of runners. Prior to this PR the only way to control the execution was via `num_workers` which basically toggled between using threads or not and configured how many threads to use if workers was greater than 1. With this proposal we can write plugins that act as a "runner", a piece of code that distributes the task across the hosts.
Writing a runner is fairly straightforward (or complex, depending of what you want to do). As an example, the runner that implements parallelization as before is this:
``` python
class ParallelRunner:
"""
ParallelRunner runs the task over each host using threads
Arguments:
num_workers: number of threads to use
"""
def __init__(self, num_workers: int = 20) -> None:
self.num_workers = num_workers
def run(self, task: Task, hosts: …
```
> proposal for runners

- nornir/plugins/connections/netconf.py
- tests/inventory_data/netconf_hosts.yaml
- tests/plugins/tasks/networking/test_netconf_capabilities.py
- tests/plugins/tasks/networking/test_netconf_connection.py
- tests/plugins/tasks/networking/test_netconf_edit_config.py
- tests/plugins/tasks/networking/test_netconf_get.py
- tests/plugins/tasks/networking/test_netconf_get_config.py
> pass ssh_config only if file exists

- nornir/core/configuration.py
- nornir/plugins/runners/__init__.py
- pyproject.toml
- tests/core/test_configuration.py
- tests/plugins/processors/test_threaded.py
> Rename ParallelRunner -> ThreadedRunner

- nornir/plugins/inventory/__init__.py
- nornir/plugins/inventory/simple.py
- pyproject.toml
- tests/core/test_registered_plugins.py
- tests/plugins/inventory/data/defaults.yaml
- tests/plugins/inventory/data/groups.yaml
- tests/plugins/inventory/data/hosts.yaml
- tests/plugins/inventory/data/netconf_hosts.yaml
- tests/plugins/inventory/test_simple_inventory.py
After discussing it with some of you I have decided to bring back `SimpleInventory` to nornir with a couple of caveats:
1. It is going to be as simple as the name indicates. Features here won't be accepted. The goal of this plugin will be to lower the barrier to entry to nornir.
2. `nornir_utils` (or some other repo) would an alternative version with extra bells and whistles (if needed)
> bring back SimpleInventory to nornir3.0.0

- nornir/core/configuration.py
- nornir/init_nornir.py
- tests/core/test_InitNornir.py
- tests/core/test_configuration.py
This causes a blank InitNornir() call to retain its current behavior (i.e. to default to using SimpleInventory).
> Default to SimpleInventory if no inventory plugin in specified (nornir3.0)

- nornir/plugins/inventory/simple.py
Allow ~ references such as this to work properly:
```yaml
---
inventory:
plugin: SimpleInventory
options:
host_file: "~/nornir_inventory/hosts.yaml"
group_file: "~/nornir_inventory/groups.yaml"
defaults_file: "~/nornir_inventory/defaults.yaml"
```
> Fixing simple inventory so that ~ works properly

- nornir/plugins/inventory/simple.py
- tests/plugins/inventory/data/hosts-nogroups.yaml
- tests/plugins/inventory/test_simple_inventory.py
Right now having a completely empty defaults.yaml file causes an obscure error message (in other words "defaults.yaml" exists, but the file is zero size).
This error would occur even if you didn't specify any `defaults_file` in SimpleInventory (as "defaults.yaml" would be automatically assumed).
The proposed behavior is consistent with what we did in Nornir 2.X.
> Allow completely empty defaults.yaml and groups.yaml files

- .github/workflows/main.yaml
- poetry.lock
- pyproject.toml
I recognize this is development only dependency, but since I am very frequently working on Netmiko (which requires TextFSM) and NAPALM, reverting back to the downrev textfsm 0.4.1 is going to cause me a lot of pain in dependency management.
So I would rather roll forward and include the windows patch here.
That branch I included won't change.
> Nornir 3.x: Use textfsm with fix for Windows

- nornir/plugins/inventory/netbox.py
- Updates NetBox name in docs
- Adds else statement to use device name if there is not a primary IP address
Fixes the NetBox plugin around issue 289, but not the rest of the plugins
> NBInventory - adds device name if no primary IP

- docs/plugins/tasks/version_control/gitlab.ipynb
- nornir/plugins/tasks/version_control/gitlab.py
- tests/plugins/tasks/version_control/test_gitlab.py
Fixes an issue with filenames (paths) & namespaced repositories, that contain characters which should be urlencoded.
This PR is basically the same as #455, but it solves some concerns that didn't receive updates.
Fixes #454
> fixes issue with urlencoding for filenames/repository in gitlab

- nornir/plugins/inventory/netbox.py
- tests/plugins/inventory/netbox/2.3.5/expected.json
- tests/plugins/inventory/netbox/2.3.5/expected_use_platform_args.json
- tests/plugins/inventory/netbox/2.3.5/expected_use_platform_args_conn_opts.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices-0.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices-1.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices-2.json
- tests/plugins/inventory/netbox/2.3.5/mocked/devices.json
- tests/plugins/inventory/netbox/2.3.5/mocked/platforms.json
- tests/plugins/inventory/netbox/2.3.5/mocked/platforms_conn_opts.json
- tests/plugins/inventory/netbox/2.8.9/expected.json
- tests/plugins/inventory/netbox/2.8.9/expected_transform_function.json
- tests/plugins/inventory/netbox/2.8.9/expected_use_platform_args.json
- tests/plugins/inventory/netbox/2.8.9/expected_use_platform_args_conn_opts.json
- tests/plugins/inventory/netbox/2.8.9/mocked/devices-0.json
- tests/plugins/inventory/netbox/2.8.9/mocked/devices-1.json
- tests/plugins/inventory/netbox/2.8.9/mocked/devices-2.json
- tests/plugins/inventory/netbox/2.8.9/mocked/devices.json
- tests/plugins/inventory/netbox/2.8.9/mocked/platforms.json
- tests/plugins/inventory/netbox/2.8.9/mocked/platforms_conn_opts.json
- tests/plugins/inventory/test_netbox.py
It would be beneficial to load napalm optional arguments as connection options based the platform a host is associated with within netbox.
I have a test group called ros (mikrotik) as follows:
With this change we can do something like the following to automatically load these into `host['connection_options']['napalm']` based on the device platform:
```
>>> from pprint import pprint
>>> from nornir import InitNornir
>>>
>>> nr = InitNornir(
...     inventory={
...         "plugin": "nornir.plugins.inventory.netbox.NBInventory",
...             "options": {
...                 "nb_url": "https://localhost:8080",
...                 "nb_token": "0123456789abcdef0123456789abcdef01234567",
...                 "ssl_verify": True,
...                 "filter_parameters": {"role": "router", …
```
> Set napalm connection options if they exist in netbox

- docs/configuration/index.rst
- docs/howto/advanced_filtering/config.yaml
Fix "Broken example for InitNornir" from #594
> Fix InitNornir example in docs/configuration/index.rst

- nornir/core/task.py
> Fixes a typo in the doc string of the result object

- docs/tutorial/inventory.ipynb
- nornir/core/inventory.py
- tests/core/test_filter.py
- tests/core/test_inventory.py
- tests/core/test_processors.py
- tests/inventory_data/groups.yaml
- tests/inventory_data/hosts.yaml
- tests/plugins/inventory/test_simple_inventory.py
- tests/plugins/processors/test_serial.py
fixes #621 
When resolving data nornir would start climbing up the tree until reach the defaults, however, the desired behaviour was to climb the tree and then back down for the next group before checking reaching the defaults, which should be checked only as a last resort.
For instance, with the tree below:
```
host
g1       g2
g11 g12
defaults
```
Before the behaviour was `host -> g1 -> g11 -> defaults` and now it is `host -> g1 -> g11 -> g12 -> g2 -> defaults`
In addition, this introduces two new methods:
1. `extended_data`, which returns the data of a given host or group, including its inherited data
2. `extended_groups`, which includes a list of groups the host or group belongs to including its inherited groups
Finally, the `dict` method was resolving the attributes of the hosts and …
> improvements to data resolution

- nornir/core/__init__.py
Fix for #666. No tests to update, and the code is de-referenced elsewhere in favor of the `data` attribute which is used now.
> remove state property from Nornir class

- nornir/core/configuration.py
I think jinja2 is a leftover from version 2
> Removing jinja2 leftover from configuration

- Dockerfile
The previous get-poetry.py and install-poetry.py installers are deprecated. 
- Changed env PATH & CURL endpoint
> DockerFile Poetry Install Update

- docs/tutorial/initializing_nornir.ipynb
Addresses #807 
I ran across this myself when reading through the tutorials last week.  I _think_ this fixes it, but I am running into docs issues.  It looks like `make sphinx` is a WIP.  While I'm on the docs subject, `make start_dev_env` mentioned in "Contributing" doesn't exist in the Makefile on `main`, either.  I'm happy to address that here or on other PR.
```shell
poetry run sphinx-build -W -b html -d docs/_build/doctrees docs docs/_build/html
Skipping virtualenv creation, as specified in config file.
Running Sphinx v4.5.0
making output directory... done
Warning, treated as error:
The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
```
> Fix broken "Configuration" link

- setup.cfg
It came to my attention on both the NAPALM and Netmiko repositories that pylama . no longer worked (for calling the linter).
Basically 'pycodestyle (pep8)' was no longer executed and it would just silently pass (even when you had linting issues). This update should fix this.
> Fix pylama breakage (pep8 reference no longer works)

- nornir/core/filter.py
- tests/core/test_filter.py
If the filter objects were comparable, I could make some tests much cleaner in my projects.
> Make filter objects F, NOT_F, AND and OR comparable

- pyproject.toml
- setup.cfg
It was a while since the last release and at work we are creating a Nornir plugin for our product but due to how the dependencies were setup for mypy-extensions in Nornir 3.3.0 I'm running into an issue when trying to add the latest version of mypy:
```bash
❯ poetry add --group dev mypy=1.5.1
Updating dependencies
Resolving dependencies... (0.0s)
Because mypy (1.5.1) depends on mypy-extensions (>=1.0.0)
and nornir (3.3.0) depends on mypy_extensions (>=0.4.1,<0.5.0), mypy (1.5.1) is incompatible with nornir (3.3.0).
And because no versions of nornir match >3.3.0,<4.0.0, mypy (1.5.1) is incompatible with nornir (>=3.3.0,<4.0.0).
```
This problem has already been fixed in the `main` branch, so it would be great if we could release a new version.
Also bumped the Python version in setup.cfg as …
> Bump version to 3.4.0

- README.md
- docs/index.rst
As per pyproject.toml Python 3.8 is the lowest version supported today, so removing the mention of 3.7.
> Change to Python 3.8

- docs/plugins/index.rst
This makes the headers for all plugins consistent.
> fixed wrong caption level for plugin documentation

- .github/workflows/main.yaml
Upgrade GitHub Actions to avoid deprecation warnings in the CI logs:
> Upgrade GitHub actions

- nornir/core/__init__.py
I'm guessing this is a leftover from older days and that it has remained since because of the noqa so it flew under the radar.
> Remove unused Host import

- nornir/core/__init__.py
- setup.cfg
The `runner` argument to Nornir is defined as being optional but we later use it as if it's always set. Adding a property that returns a `RunnerPlugin` or raises an error, with this we can also remove the `strict_optional = False` bypass in the mypy config.
> Add property for optional runner

- poetry.lock
- pyproject.toml
Fixes #917 
`setuptools` 42.0.0 is the first version that supports Python 3.8, the minimum Python requirement.
> Add `setuptools` to dependencies

- .github/workflows/main.yaml
- CONTRIBUTING.rst
- Makefile
- README.md
- docs/conf.py
- nornir/core/__init__.py
- nornir/core/configuration.py
- nornir/core/filter.py
- nornir/core/helpers/jinja_helper.py
- nornir/core/inventory.py
- nornir/core/plugins/runners.py
- nornir/core/processor.py
- nornir/core/state.py
- nornir/core/task.py
- nornir/plugins/inventory/simple.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/core/test_InitNornir.py
- tests/core/test_configuration.py
- tests/core/test_connections.py
- tests/core/test_inventory.py
- tests/core/test_processors.py
- tests/core/test_tasks.py
- tests/plugins/processors/test_threaded.py
This PR removes black and isort and instead uses ruff to validate the formatting of the code along with the sorting of imports.
Due to minor changes between Black and Ruff a few lines have been changed within the codebase.
> Replace black & isort with ruff for formatting

- docs/conf.py
- pyproject.toml
Move global rule for commented out code to only apply to docs/conf.py, remove shebang in docs/conf.py as the file is not executable.
> Move section for commented out code, remove shebang

- nornir/core/__init__.py
- pyproject.toml
The first argument in `__exit__` should be annotated with `object` or `type[BaseException] | None
> Fix Ruff PYI036 - Type annotations for context manager exit

- README.md
This is to reflect the current default branch on GitHub where the `develop` branch no longer exists.
Note, due to #935 this will cause the reported value to drop until that issue is fixed.
> Switch coverage badge from develop to main branch

- SECURITY.md
(minor) fix dependency spelling in `SECURITY.md`
> SECURITY.md - (minor) fix dependency spelling

- docs/tutorial/processors.ipynb
fix processors class docs hyperlink (issue #593)
> fix processors class docs hyperlink (issue #593)

- docs/tutorial/failed_tasks.ipynb
- docs/tutorial/initializing_nornir.ipynb
> fix docs tutorial links

- docs/howto/handling_connections.ipynb
fix broken link in handling_connections.ipynb howto doc
> fix broken link in handling_connections.ipynb howto doc

- nornir/__init__.py
`pkg_resources` is deprecated in Python 3.12 (https://setuptools.pypa.io/en/latest/pkg_resources.html), and `importlib.metadata` is available since Python 3.8 (https://docs.python.org/3.12/library/importlib.metadata.html)
> Replace pkg_resources with importlib.metadata

- pyproject.toml
- tests/conftest.py
- tests/core/test_InitNornir.py
- tests/core/test_configuration.py
- tests/core/test_connections.py
- tests/core/test_filter.py
- tests/core/test_inventory.py
- tests/core/test_processors.py
- tests/core/test_registered_plugins.py
- tests/core/test_tasks.py
- tests/plugins/inventory/test_simple_inventory.py
- tests/plugins/processors/test_serial.py
- tests/plugins/processors/test_threaded.py
- tests/wrapper.py
This PR corrects most of the type hints within ./tests. There are a few remaining for which I added more specific overrides to ignore those rules.
> Update type hints within ./tests
